services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app    
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    container_name: postgres  
